
package main.java.com.example.demo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Big", targetNamespace = "http://demo.example.com.java.main/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Big {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "kmToMiles", targetNamespace = "http://demo.example.com.java.main/", className = "main.java.com.example.demo.KmToMiles")
    @ResponseWrapper(localName = "kmToMilesResponse", targetNamespace = "http://demo.example.com.java.main/", className = "main.java.com.example.demo.KmToMilesResponse")
    public Double kmToMiles(
        @WebParam(name = "arg0", targetNamespace = "")
        Double arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "nodesToKm", targetNamespace = "http://demo.example.com.java.main/", className = "main.java.com.example.demo.NodesToKm")
    @ResponseWrapper(localName = "nodesToKmResponse", targetNamespace = "http://demo.example.com.java.main/", className = "main.java.com.example.demo.NodesToKmResponse")
    public Double nodesToKm(
        @WebParam(name = "arg0", targetNamespace = "")
        Double arg0);

}
